apiVersion: v1
kind: Service
metadata:
  name: {{ include "devstandards-hub.fullname" . }}
  labels:
    {{- include "devstandards-hub.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "devstandards-hub.selectorLabels" . | nindent 4 }}
